name: Versioning deploys
on:
  pull_request:
    types:
      - closed

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: robolancers/lancer-deploy-tool@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}